# Generated by Django 5.1.4 on 2025-01-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0003_answer_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="modified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="modified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
