# Generated by Django 5.1.4 on 2025-01-12 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0005_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pybo.question",
            ),
        ),
    ]
