# Generated by Django 5.1.4 on 2025-01-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0006_alter_comment_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="modfied_date",
            new_name="modified_date",
        ),
    ]
